language: node_js

node_js:
  - stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install --ignore-engines
  - yarn run build

script:
  - yarn run test