FORMAT: 1A
HOST: http://mikestumpf.com/

# mikestumpf.com

API to support main site

## Posts Collection [/api/loadMorePosts]

### Load More Posts [POST]

Gets additional post objects based on pagination parameter

+ Request (application/json)

        {
            "page": 1
        }

+ Response 200 (text/html; charset=utf-8)

    + Body

            <div class="post" onclick="window.location.href='/music/new-project'" data-group="1">
                <div class="content-post">
                    <h3 class="post-title">New Project</h3>
                    <h5 class="post-date">
                        <i class="fa fa-calendar"></i>December 28, 2015
                    </h5>
                    <hr>
                    <div class="post-excerpt">
                        <p>A new guitar, a new philosophy, and a new endeavor.</p>
                    </div>
                </div>
            </div>
